---
title: "App Bonds Portfolio Plots"
output: html_document
runtime: shiny
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
for (r2dii_pkg in c("r2dii.colours", "r2dii.plot", "r2dii.utils", "r2dii.climate.stress.test")) {
  if (!(r2dii_pkg %in% installed.packages()[,"Package"])) {
    install.packages(file.path(getwd(), "packages", r2dii_pkg),
                     repos = NULL,
                     type = "source", 
                     character.only = TRUE)
  }
}

requirements <- c("ggplot2", "dplyr", "tidyverse", "scales", "cowplot", "shiny", "slickR", "svglite", "shinyWidgets"
                  )
for (pkg in requirements) {
  if (!(pkg %in% installed.packages()[,"Package"])) {
    install.packages(pkg, character.only = TRUE)
  }
  
}
```

```{r echo=FALSE, message=FALSE, results=FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(scales)
library(cowplot)
library(shiny)
library(slickR)
library(svglite)
library(shinyWidgets)
library(r2dii.colours)
library(r2dii.plot)
library(r2dii.utils)
source(file.path(getwd(), "src", "dataload.R"))
source(file.path(getwd(), "src", "utils.R"))
source(file.path(getwd(), "src", "portfolio_plots.R"))
source(file.path(getwd(), "src", "compute.R"))
```

<!-- ```{r} -->

<!-- fileInput("equity_input_file", "Choose CSV File") -->

<!-- fileInput("bonds_input_file", "Choose CSV File") -->

<!-- fileInput("trisk_outputs_folder_files", "Choose CSV File") -->

<!-- ``` -->

```{r}
# equity_input_path <- file.path(getwd(), "data", "exposures_per_ar_id.csv")
portfolio_input_path <- file.path(getwd(), "data", "portfolio_data_template.csv")
trisk_output_path <- file.path(getwd(), "data", "trisk_runs")
color_gradient <- c("#FFC0C0", "#FF8888", "#FF6666", "#FF4444", "#FF2222", "#FF0000")
```

Read in the data. Put the outputs of a stress test run into 'data' folder of this project to run the code successfully.

```{r, results=FALSE, warning=FALSE}
################################################################################
# LOAD Exposure data
# equity_exposures <- load_equity_exposures(equity_input_path)
## LOAD Bond data
portfolio_data <- load_portfolio_data(portfolio_input_path)

################################################################################
# LOAD in different crispy runs
all_crispy <- load_multi_crispy_outputs(trisk_output_path)
```

1. To download a plot : right-click > save as > choose a filename and add .svg (if from caroussel) or .png (if from long display) at the end of the file.
2. Activate the caroussel plot mode 

```{r, echo=FALSE, results=FALSE, warning=FALSE}
#############################################################
#############################################################
################# DEBUG ONLY TODO REMOVE #####################

##randomly shuffle dataset to create a 2nd shock_year
all_crispy_newshockyear = all_crispy %>%
  select(-c(company_name))  %>%
  bind_cols(all_crispy %>% select(company_name)%>% sample_frac(size = 1)) %>%
  mutate(shock_year=2020)
all_crispy_newshockyear <- all_crispy_newshockyear %>% mutate(
  growth_rate = if_else(scenario_duo == "WEO2021_STEPS__WEO2021_SDS", 1, growth_rate)
)
all_crispy <- all_crispy %>%
  bind_rows(all_crispy_newshockyear)


##randomly assign company_ids from portfolio to company_name in crispy
# to add diversity
company_to_name <-
  dplyr::bind_cols(
    (all_crispy %>% distinct(company_name) %>% sample_frac(size = 1))[1:nrow(equity_exposures %>% distinct(company_id)), ],
    equity_exposures %>% distinct(company_id) %>% sample_frac(size = 1)
  )
all_crispy <- all_crispy %>% inner_join(company_to_name)


################# DEBUG ONLY TODO REMOVE #####################
#############################################################
#############################################################

```

# PLOTS

```{r br, echo=FALSE}
# UI
inputPanel(
  selectInput(
    "plot_variable",
    "Choose variable to analyze in plots",
    choices = c(
      "scenario_geography",
      "risk_free_rate",
      "discount_rate",
      "dividend_rate",
      "growth_rate",
      "shock_year"
    ),
    selected = "shock_year",
    multiple = FALSE
  ),
  
  checkboxGroupInput(
    "variable_values",
    label = "variable values",
    choices = c()),
  
  checkboxGroupInput(
  "scenario_names",
  label = "Pick scenarios",
  choices = unique(all_crispy$scenario_duo),
  selected= unique(all_crispy$scenario_duo))
)

numericInput(inputId = "pd_max_y",
             label="set maximum display value for PD plots",
             value=1,
             min=0,
             max=1
             )

prettySwitch(
   inputId = "toggleBtn",
   label = "Collapse/Reset plots", 
   value = FALSE
)



```

```{r message=FALSE, warning=FALSE, echo=FALSE}
# UI UPDATES

observe({
  if (!is.null(input$plot_variable)) {
    available_values <- all_crispy %>% # TODO all_crispy ou filtered_crispy() ?
      dplyr::distinct(!!rlang::sym(input$plot_variable)) %>%
      dplyr::pull()
    updateCheckboxGroupInput(session,
                             "variable_values",
                             choices = available_values,
                             selected = available_values)
  }
})


toggle_caroussel <-
  reactive({
    if (is.null(input$toggleBtn)) {
      F
    } else {
      input$toggleBtn
    }
  })


plot_variable.r <-
  reactive({
    if (is.null(input$plot_variable)) {
      "shock_year"
    } else {
      input$plot_variable
    }
  })
```


```{r, echo=FALSE}
# filter dataset

filtered_crispy <- reactive({
  if (!is.null(input$plot_variable) &
      !is.null(input$variable_values) &
      !is.null(input$scenario_names)){
  all_crispy %>%
    dplyr::filter(
      !!rlang::sym(input$plot_variable) %in% c(input$variable_values),
      scenario_duo %in% c(input$scenario_names)
    )
  }
  else{
    all_crispy
  }
})

```

# Compute indicators
```{r}
scenario_sector_weights <- reactive({compute_scenario_sector_weights(filtered_crispy())})
```


# MEAN PD DIFF SY PLOT

```{r, echo=FALSE}


tp_list <- reactive({
  make_mean_pd_diff_sy_plots(filtered_crispy(),
                             bond_data,
                             plot_variable.r(),
                             color_gradient)
})


renderUI({
  if (toggle_caroussel()) {
    slickR::slickROutput("slick_output", width = '100%', height = '200%')
  } else{
    plot_output_list <- lapply(1:length(tp_list()), function(i) {
      plotname <- paste("plot", i, sep = "")
      plotOutput(plotname)
    })
    do.call(tagList, plot_output_list)
  }
})

observe({
  if (toggle_caroussel()) {
    output$slick_output <- slickR::renderSlickR({
      svg_plot_list <- lapply(tp_list(), function(x) {
        svglite::xmlSVG(show(x), standalone = TRUE)
      })
      slickR::slickR(svg_plot_list,) +
        slickR::settings(
          slidesToShow = 2,
          centerMode = TRUE,
          dots = T,
          infinite = F
        )
    })
  }
  else{
    for (i in 1:length(tp_list())) {
      local({
        my_i <- i
        plotname <- paste("plot", my_i, sep = "")
        output[[plotname]] <- renderPlot({
          tp_list()[[my_i]] + ggplot2::scale_y_continuous(limits=c(0, input$pd_max_y)) + ggplot2::coord_flip() 
        })
      })
    }
  }
})

```


## EL PLOT LOOP SY

```{r, echo=FALSE}
tp_list2 <- reactive({
  make_expected_loss_plot(
    filtered_crispy(),
    bond_data,
    scenario_sector_weights(),
    plot_variable.r(),
    color_gradient
  )
})


renderUI({
  if (toggle_caroussel()) {
    slickR::slickROutput("slick_output2", width = '100%', height = '200%')
  } else{
    plot_output_list <- lapply(1:length(tp_list2()), function(i) {
      plotname <- paste("plot2", i, sep = "")
      plotOutput(plotname)
    })
    do.call(tagList, plot_output_list)
  }
})

observe({
  if (toggle_caroussel()) {
    output$slick_output2 <- slickR::renderSlickR({
      svg_plot_list <- lapply(tp_list2(), function(x) {
        svglite::xmlSVG(show(x), standalone = TRUE)
      })
      slickR::slickR(svg_plot_list,) +
        slickR::settings(
          slidesToShow = 2,
          centerMode = TRUE,
          dots = T,
          infinite = F
        )
    })
  }
  else{
    for (i in 1:length(tp_list2())) {
      local({
        my_i <- i
        plotname <- paste("plot2", my_i, sep = "")
        output[[plotname]] <- renderPlot({
          tp_list2()[[my_i]] + ggplot2::coord_flip() 
        })
      })
    }
  }
})
```

<!-- # Discount Rate Plots -->

<!-- ```{r, echo=FALSE} -->
<!-- tp_list3 <- reactive({ -->
<!--   make_discount_rate_plot( -->
<!--     filtered_crispy(), -->
<!--     bond_data, -->
<!--     scenario_sector_weights(), -->
<!--     plot_variable.r(), -->
<!--     color_gradient -->
<!--   ) -->
<!-- }) -->


<!-- renderUI({ -->
<!--   if (toggle_caroussel()) { -->
<!--     slickR::slickROutput("slick_output3", width = '100%', height = '200%') -->
<!--   } else{ -->
<!--     plot_output_list <- lapply(1:length(tp_list3()), function(i) { -->
<!--       plotname <- paste("plot3", i, sep = "") -->
<!--       plotOutput(plotname) -->
<!--     }) -->
<!--     do.call(tagList, plot_output_list) -->
<!--   } -->
<!-- }) -->

<!-- observe({ -->
<!--   if (toggle_caroussel()) { -->
<!--     output$slick_output2 <- slickR::renderSlickR({ -->
<!--       svg_plot_list <- lapply(tp_list3(), function(x) { -->
<!--         svglite::xmlSVG(show(x), standalone = TRUE) -->
<!--       }) -->
<!--       slickR::slickR(svg_plot_list,) + -->
<!--         slickR::settings( -->
<!--           slidesToShow = 2, -->
<!--           centerMode = TRUE, -->
<!--           dots = T, -->
<!--           infinite = F -->
<!--         ) -->
<!--     }) -->
<!--   } -->
<!--   else{ -->
<!--     for (i in 1:length(tp_list3())) { -->
<!--       local({ -->
<!--         my_i <- i -->
<!--         plotname <- paste("plot3", my_i, sep = "") -->
<!--         output[[plotname]] <- renderPlot({ -->
<!--           tp_list3()[[my_i]] + ggplot2::scale_y_continuous(limits=c(0, 0.5)) + ggplot2::coord_flip()  -->
<!--         }) -->
<!--       }) -->
<!--     } -->
<!--   } -->
<!-- }) -->
<!-- ``` -->
